apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-ollama
  namespace: ai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 75Gi
  volumeName: ollama-pv
  storageClassName: ""   # ✅ Must match the PV

