apiVersion: v1
kind: Pod
metadata:
  name: test-ollama-vol
  namespace: ai
spec:
  containers:
  - name: test
    image: busybox
    command: [ "sh", "-c", "sleep 3600" ]
    volumeMounts:
    - name: ollama-data
      mountPath: /data
  volumes:
  - name: ollama-data
    persistentVolumeClaim:
      claimName: open-webui-ollama

