# save as: install-os-tools.yaml
- name: Install useful OS tools
  hosts: all
  become: yes
  tasks:
    - name: Ensure apt cache is updated
      ansible.builtin.apt:
        update_cache: yes

    - name: Install common OS tools
      ansible.builtin.apt:
        name:
          - ripgrep
          - curl
          - htop
          - vim
          - git
          - wget
          - unzip
        state: present

- name: Add kubectl alias for david
  hosts: all
  become: yes
  vars:
    user: david
  tasks:
    - name: Ensure kubectl alias in .bashrc
      ansible.builtin.lineinfile:
        path: "/home/{{ user }}/.bashrc"
        line: "alias k='kubectl'"
        create: yes
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0644"
        insertafter: EOF

