- name: Configure Git global settings
  hosts: all
  become: false   # no need for root, runs as the target user
  vars:
    user: david

  tasks:
    - name: Set Git global user.name
      community.general.git_config:
        name: user.name
        scope: global
        value: "David Kiser"

    - name: Set Git global user.email
      community.general.git_config:
        name: user.email
        scope: global
        value: "dgkiser@yahoo.com"

    - name: Add NO_AT_BRIDGE env var to .bashrc
      ansible.builtin.lineinfile:
        path: "/home/{{ user }}/.bashrc"
        line: 'export NO_AT_BRIDGE=1'
        create: yes
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0644"
        insertafter: EOF

    - name: Add kubectl alias for david
      hosts: all
      become: yes
      vars:
        user: david
      tasks:
        - name: Ensure kubectl alias in .bashrc
          ansible.builtin.lineinfile:
            path: "/home/{{ user }}/.bashrc"
            line: "alias k='kubectl'"
            create: yes
            owner: "{{ user }}"
            group: "{{ user }}"
            mode: "0644"
            insertafter: EOF

        - name: Ensure kpodsh alias in .bashrc
          ansible.builtin.lineinfile:
            path: "/home/{{ user }}/.bashrc"
            line: "alias kpodsh='~/Code/script/kpodsh.sh'"
            create: yes 
            owner: "{{ user }}"
            group: "{{ user }}"
            mode: "0644"
            insertafter: EOF
