# save as: install-os-tools.yaml
- name: Install useful OS tools
  hosts: all
  become: yes
  tasks:
    - name: Ensure apt cache is updated
      ansible.builtin.apt:
        update_cache: yes

    - name: Install common OS tools
      ansible.builtin.apt:
        name:
          - ripgrep
          - curl
          - htop
          - vim
          - git
          - wget
          - unzip
        state: present
