apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-data
  namespace: ai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: longhorn

