apiVersion: v1
kind: Service
metadata:
  name: open-webui
  namespace: ai
spec:
  selector:
    app.kubernetes.io/instance: open-webui
  ports:
    - name: http
      port: 80           # Traefik still connects to port 80
      targetPort: 8080   # Forwarded to container's 8080


